MPPLKelompok/advanced/backend/models/User.php
<?php

namespace backend\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property resource $image
 * @property string $role
 */

class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'auth_key', 'password_hash', 'email', 'created_at', 'updated_at', 'image', 'role'], 'required'],
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['image'], 'string'],
            [['username', 'password_hash', 'password_reset_token', 'email'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['role'], 'string', 'max' => 30],
            [['username'], 'unique'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Email',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'image' => 'Image',
            'role' => 'Role',
        ];
    }

    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    public function getPassword()
    {
        return Yii::$app->getSecurity()->decryptByPassword($this->password_hash, 'THE_SECRET_YOU_ALREADY_HAVE_CHOOSEN');
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

MPPLKelompok/advanced/backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\User;
use backend\models\UserSearch;
use backend\models\Satpam;
use backend\models\Mahasiswa;
use backend\models\Keasramaan;
use backend\models\SatpamSearch;
use backend\models\KeasramaanSearch;
use backend\models\MahasiswaSearch;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [          
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login','view', 'createasrama','createmahasiswa', 'createsatpam', 'delete' , 'viewcek',  'updateas' ,'updatesat','updatema', 'updatecekadmin', 'updatemahasiswa', 'updateasrama',  'updatesatpam', 'update', 'updateadmin'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],            

            ], 
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
   

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */



    

    public function actionUpdatecekadmin($id){
        $user = User::findOne($id);

        if($user->role == 'Keasramaan'){
            return $this->redirect(['updateasrama', 'id' => $user->id]);
        }

        else if ($user->role == 'Admin') {
            return $this->redirect(['updateadmin', 'id' => $user->id]);
        }

        else if($user->role == 'Satpam'){
            return $this->redirect(['updatesatpam', 'id' => $user->id]);
        }

        else if ($user->role == 'Mahasiswa') {
           return $this->redirect(['updatemahasiswa', 'id' => $user->id]);
        }        
    }

//OptionUpdate di admin
    public function actionUpdateasrama($id)
    {
        
        $model = $this->findModel($id);
        $modelk = Keasramaan::findOne($model->username);

        if ($model->load(Yii::$app->request->post()) && $modelk->load(Yii::$app->request->post())) {                      
            $hash = Yii::$app->getSecurity()->generatePasswordHash($model->password_hash);
            $model->password_hash = $hash;


            $model->updated_at = date("Y-m-d").' '.date("h:i:s a");
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->image = file_get_contents($model->image->tempName);   
            
            $modelk->nid = $model->username;   

            if($model->save(false) && $modelk->save(false)){
                         
            }
            return $this->redirect(['updateasrama', 'id' => $model->id]);
                                
        } else {
            return $this->render('updateasrama', [
                'model' => $model,
                'modelk' => $modelk,
            ]);
        }
    }


    public function actionUpdatemahasiswa($id)
    {
        
        $model = $this->findModel($id);
        $modelk = Mahasiswa::findOne($model->username);

        if ($model->load(Yii::$app->request->post()) && $modelk->load(Yii::$app->request->post())) {                      
            $hash = Yii::$app->getSecurity()->generatePasswordHash($model->password_hash);
            $model->password_hash = $hash;


            $model->updated_at = date("Y-m-d").' '.date("h:i:s a");
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->image = file_get_contents($model->image->tempName);   
            
            $modelk->nim = $model->username;   

            if($model->save(false) && $modelk->save(false)){
                         
            }
            return $this->redirect(['updatemahasiswa', 'id' => $model->id]);
                                
        } else {
            return $this->render('updatemahasiswa', [
                'model' => $model,
                'modelk' => $modelk,
            ]);
        }
    }

    public function actionUpdateadmin($id)
    {
        
        $model = $this->findModel($id);        

        if ($model->load(Yii::$app->request->post()) && $modelk->load(Yii::$app->request->post())) {   
            $hash = Yii::$app->getSecurity()->generatePasswordHash($model->password_hash);
            $model->password_hash = $hash;                              
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->image = file_get_contents($model->image->tempName);               

            $model->updated_at = date("Y-m-d").' '.date("h:i:s a");

            $model->save();

            return $this->redirect(['viewcek', 'id' => $model->id]);             
            }
             else {
            return $this->render('updateadmin', [
                'model' => $model,                
            ]);
        }
    }

        public function actionUpdatesatpam($id)
    {
        
        $model = $this->findModel($id);
        $modelk = Satpam::findOne($model->username);

        if ($model->load(Yii::$app->request->post()) && $modelk->load(Yii::$app->request->post())) {                      
            $hash = Yii::$app->getSecurity()->generatePasswordHash($model->password_hash);
            $model->password_hash = $hash;


            $model->updated_at = date("Y-m-d").' '.date("h:i:s a");
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->image = file_get_contents($model->image->tempName);   
            
            $modelk->username = $model->username;   

            if($model->save(false) && $modelk->save(false)){
                         
            }
            return $this->redirect(['view', 'id' => $model->id]);
                                
        } else {
            return $this->render('updatesatpam', [
                'model' => $model,
                'modelk' => $modelk,
            ]);
        }
    }



     public function actionCreateasrama()
    {
        $model = new User();
        $modelk = new Keasramaan();

        if ($model->load(Yii::$app->request->post()) && $modelk->load(Yii::$app->request->post())) {
            $hash = Yii::$app->getSecurity()->generatePasswordHash($model->password_hash);
            $model->password_hash = $hash;
            $model->status="10";
            $model->generateAuthKey();
            $model->created_at = date("Y-m-d").' '.date("h:i:s a");
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->image = file_get_contents($model->image->tempName);   

            $modelk->nid = $model->username;   
            $model->save(false);
            $modelk->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
                                
        } else {
            return $this->render('createasrama', [
                'model' => $model,
                'modelk' => $modelk,
            ]);
        }
    }

          public function actionCreatemahasiswa()
    {
        $model = new User();
        $modelk = new Mahasiswa();

        if ($model->load(Yii::$app->request->post()) && $modelk->load(Yii::$app->request->post())) {
            $hash = Yii::$app->getSecurity()->generatePasswordHash($model->password_hash);
            $model->password_hash = $hash;
            $model->status="10";
            $model->generateAuthKey();
            $model->created_at = date("Y-m-d").' '.date("h:i:s a");
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->image = file_get_contents($model->image->tempName);   

            $modelk->nim = $model->username;   
            $model->save(false);
            $modelk->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
                                
        } else {
            return $this->render('createmahasiswa', [
                'model' => $model,
                'modelk' => $modelk,
            ]);
        }
    }


    public function actionCreatesatpam()
    {
        $model = new User();
        $modelk = new Satpam();

        if ($model->load(Yii::$app->request->post()) && $modelk->load(Yii::$app->request->post())) {
            $hash = Yii::$app->getSecurity()->generatePasswordHash($model->password_hash);
            $model->password_hash = $hash;
            $model->status="10";
            $model->generateAuthKey();
            $model->created_at = date("Y-m-d").' '.date("h:i:s a");
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->image = file_get_contents($model->image->tempName);   

MPPLKelompok/advanced/backend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use backend\models\User;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Dropdown;
use yii\widgets\Menu;

/* @var $this yii\web\View */
/* @var $model backend\models\User */
/* @var $form yii\widgets\ActiveForm */

use yii\bootstrap\NavBar;
use yii\bootstrap\Nav;

echo Nav::widget([
    'items' => [
        ['label' => 'Keasramaan', 'url' => ['/user/createasrama']],
        ['label' => 'Mahasiswa', 'url' => ['/user/createmahasiswa']],
        ['label' => 'Satpam', 'url' => ['/user/createsatpam']],
    ],
    'options' => ['class' => 'nav nav-tabs'],
]);



?>

<div class="user-form">
<br>
    <?php $form = ActiveForm::begin(['options' => ['enctype'=>'multipart/form-data']]); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($modelk, 'nama')->textInput(['maxlength' => true]) ?>   

    <?= $form->field($modelk, 'no_telepon')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password_hash')->textInput(['maxlength' => true]) ?>    

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'image')->fileInput()?>  
    

    <?= $form->field($model,'role')->dropDownList(['Keasramaan'=>'Keasramaan', 'Mahasiswa'=> 'Mahasiswa', 'Satpam' => 'Satpam'],['prompt' => '--Select Role--'])?>

    <div class="form-group">
        <?= Html::submitButton( 'Create' , ['class' => 'btn btn-success' ]) ?>
        <?= Html::a('Back', ['site/index'], ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

MPPLKelompok/advanced/backend/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'role') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

MPPLKelompok/advanced/backend/views/user/createasrama.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\User */

$this->title = 'Create Keasramaan';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">
   
    <?= $this->render('_form', [
        'model' => $model,
        'modelk' => $modelk,
    ]) ?>

</div>

MPPLKelompok/advanced/backend/views/user/createmahasiswa.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\bootstrap\checkBoxList;
use backend\models\User;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Dropdown;
use yii\widgets\Menu;

/* @var $this yii\web\View */
/* @var $model backend\models\User */
/* @var $form yii\widgets\ActiveForm */

use yii\bootstrap\NavBar;
use yii\bootstrap\Nav;


$this->title = 'Create Mahasiswa';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

echo Nav::widget([
    'items' => [
        ['label' => 'Keasramaan', 'url' => ['/user/createasrama']],
        ['label' => 'Mahasiswa', 'url' => ['/user/createmahasiswa']],
        ['label' => 'Satpam', 'url' => ['/user/createsatpam']],
    ],
    'options' => ['class' => 'nav nav-tabs'],
]);



?>

<div class="user-form">
<br>
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password_hash')->textInput(['maxlength' => true]) ?>    

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>    

    <?= $form->field($modelk, 'nama')->textInput(['maxlength' => true]) ?>

    <?= $form->field($modelk, 'notlpon')->textInput(['maxlength' => true]) ?>

    <?= $form->field($modelk, 'alamat')->textInput(['maxlength' => true]) ?>    

    <?= $form->field($modelk, 'lantai')->textInput(['maxlength' => true]) ?>

    <?= $form->field($modelk, 'kamar')->textInput(['maxlength' => true]) ?>

    <?= $form->field($modelk, 'notlponortu')->textInput(['maxlength' => true]) ?>

    <?= $form->field($modelk, 'jenisKelamin')->radioList(['L'=> 'Laki-Laki', 'P' => 'Perempuan']) ?> 
    
    <?= $form->field($model, 'image')->fileInput()?>  

    <?= $form->field($model,'role')->dropDownList(['Admin'=>'Admin', 'Mahasiswa'=> 'Mahasiswa', 'Satpam' => 'Satpam'],['prompt' => '--Select Role--'])?>


    <div class="form-group">
           <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>           
        <?= Html::a('Back', ['site/index'], ['class' => 'btn btn-primary']) ?>
    </div>


    <?php ActiveForm::end(); ?>

</div>

MPPLKelompok/advanced/backend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\User */

$this->title = 'Update User: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

MPPLKelompok/advanced/backend/views/user/updateadmin.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Keasramaan */
/* @var $form yii\widgets\ActiveForm */


$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

echo ' <center><img  width="200" height="200" src="data:image/jpeg;base64,'.base64_encode($model->image).'"/></center>';
?>

<div class="keasramaan-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>  

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password_hash')->textInput(['maxlength' => true]) ?>  

    <?= $form->field($model, 'image')->fileInput()?>  

    <div class="form-group">
        <?= Html::submitButton('Update', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Back', ['viewcek', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

MPPLKelompok/advanced/backend/views/user/updatema.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Satpam */
/* @var $form yii\widgets\ActiveForm */

$this->title = $modelk->nama;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
echo ' <center><img  width="200" height="200" src="data:image/jpeg;base64,'.base64_encode($model->image).'"/></center>';
?>

<div class="satpam-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($modelk, 'nama')->textInput(['maxlength' => true]) ?>

    <?= $form->field($modelk, 'notlpon')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'image')->fileInput()?>  

    <div class="form-group">
        <?= Html::submitButton('Update', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Back', ['viewadmin', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
    

MPPLKelompok/advanced/backend/views/user/updatesat.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Satpam */
/* @var $form yii\widgets\ActiveForm */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

echo ' <center><img  width="200" height="200" src="data:image/jpeg;base64,'.base64_encode($model->image).'"/></center>';
?>

<div class="satpam-form">

	<?php $form = ActiveForm::begin(); ?>
	<?= $form->field($modelk, 'username')->textInput(['readonly' => true]) ?>    

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>    

    <?= $form->field($modelk, 'nama')->textInput(['maxlength' => true]) ?>

    <?= $form->field($modelk, 'notelepon')->textInput(['maxlength' => true]) ?>       
    
    <?= $form->field($model, 'image')->fileInput()?>  


    <div class="form-group">
        <?= Html::submitButton('Update', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Back', ['viewcek', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

MPPLKelompok/advanced/backend/views/user/updatesatpam.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use backend\models\User;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Dropdown;
use yii\widgets\Menu;

/* @var $this yii\web\View */
/* @var $model backend\models\User */
/* @var $form yii\widgets\ActiveForm */

use yii\bootstrap\NavBar;
use yii\bootstrap\Nav;


$this->title = 'Update Satpam: ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="user-form">
<br>
    <?php $form = ActiveForm::begin(['options' => ['enctype'=>'multipart/form-data']]); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($modelk, 'nama')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password_hash')->textInput(['maxlength' => true]) ?>    

    <?= $form->field($modelk, 'notelepon')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'image')->fileInput()?>  

    <?= $form->field($model,'role')->dropDownList(['Admin'=>'Admin', 'Mahasiswa'=> 'Mahasiswa', 'Satpam' => 'Satpam'],['prompt' => '--Select Role--'])?>

    <div class="form-group">
        <?= Html::submitButton( 'Create' , ['class' => 'btn btn-success' ]) ?>    
       <?= Html::a('Back', ['site/index'], ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

MPPLKelompok/advanced/backend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\User */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">
    

    <p>
        <?= Html::a('Update', ['updatecekadmin', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'auth_key',
            'password_hash',
            'password_reset_token',
            'email:email',
            'status',
            'created_at',
            'updated_at',
            'role',
        ],
    ]) ?>

</div>